### ISSUE TITLE
Help with modifying this app to be self-hosted

### ISSUE THREAD

**Issue by photon-schiesser** [sqall01/alertR-Push-Android#2]
Hi there!

I am interested in forking/modifying this Android app such that I could use my own Firebase account and/or my own server to do the push notifications. I am hoping you could help me with this.

I am just looking for a head start, I don't need you to walk me through it. Just a quick overview of what API I need on my own server (instead of your alertR.de server) and what needs changed in the alertR Android app (presumably it is hard-coded to your Firebase account).

This is great work! Thank you!

**Comment by sqall01** [comment]
Hi,

you need this component on your server:

https://github.com/sqall01/alertR-Push-Server

and to set up your Firebase account. On how to do this, please refer to the google Firebase manual for messaging.

Cheers,
sqall
