### ISSUE TITLE
Clear message history in the Android app

### ISSUE THREAD

**Issue by norey** [sqall01/alertR-Push-Android#3]
Hello,

Is it possible to clear the message history in the Android app? I couldn't find anything related to that. Am I missing something?

Thanks

**Comment by sqall01** [comment]
Hi,

no at the moment the feature does not exist. However, this seems like an easy change. I will check if I find the time on the weekend to add this feature.

Cheers,
sqall

**Comment by sqall01** [comment]
The most problems in doing that were making Android Studio (like always). The feature is now there and pushed to the Play Store.

Cheers,
sqall
